### PR TITLE
Replicates the structure of the source tree

### PR DESCRIPTION
**Pull request by 92bondstreet**
Hi, 

I jut get the source code of @karlspalding from PR #236.

I hope it will be useful !

Yassine.

### CODE REVIEW

**Comment by avetisk** [comment]
+1

**Comment by xzen** [comment]
+1

**Comment by ccoVeille** [comment]
+1 definitely useful !

**Comment by aurelienappere** [comment]
+1

**Comment by lemacbacon** [comment]
+1

**Comment by brainlesscurls** [comment]
+1

**Comment by EmmanuelleDesirliste** [comment]
+1

**Comment by AlexandreMathieu** [comment]
Good idea.

**Comment by joaomilho** [comment]
Looks pretty much identical to #336 . Again, what can be done to help this reach master? :D

**Comment by abritinthebay** [comment]
This *needs* to be merged

**Comment by hxgdzyuyi** [comment]
+1

**Comment by abritinthebay** [comment]
Docco has basically been abandoned at this point - no updates in over a year - mostly 2-3 years.

Thinking of forking it...

**Comment by mercmobily** [comment]
Nope, it's not abandoned... and any other fork has quickly lost steam. The author doesn't work on it full time, but he's basing maintenance on community PRs which is fine...

**Comment by abritinthebay** [comment]
In the sense that it only seems to merge changes that add language support. Not features (like this one).

Practically speaking - it's dead.

**Comment by jashkenas** [comment]
I've just merged in https://github.com/jashkenas/docco/commit/0deced331dd284ffbb6f28f61a17d7ea8ee3ca7a, and published it out as Docco 0.8.0. 

Feel free to give it a try and let me know if it gives you any trouble...

**Comment by mercmobily** [comment]
@jashkenas Thanks Jeremy!

**Pull request closed without merging**
